### ISSUE TITLE
Replace Int with Long data type for various count values

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#176]
This issue has been copied from here: https://github.com/sys1yagi/mastodon4j/pull/90

Description of the pull request author:
gson throws NumberFormatException if followersCount and so on exceed Int limit.
It may be desirable for other Int fields(e.g. Status class's favouritesCount), too.

**Comment by andregasser** [comment]
@lamrongol We have started to continue development of Mastodon4J as part of the BigBone project. Therefore, I have copied your issue report over to our project in order to fix it in our code as well. 

Coud you eventually provide an example of an account where such an `Int` limit of `2,147,483,647` was exceeded? Thank you very much.

**Comment by andregasser** [comment]
I went through all our current entities and found the following fields that we should consider fixing:

Account.kt
- followers_count
- following_count
- statuses_count

InstanceStats.kt
- userCount
- statusCount
- domainCount

Poll.kt
- votesCount
- votersCount
- Option.votesCount

Status.kt
- reblogsCount
- favouritesCount
- repliesCount

**Comment by lamrongol** [comment]
I found this bug when using Streaming and it is impossible to know what it was trying to process before the error occurred (I've cloned the mastodon4j source code, but could not get it to work due to different Gradle versions, etc.).

```
Handler handler = new Handler() {
    //Error occurs
    @Override
    public void onStatus(@NotNull Status status) {
        System.out.println(status.getContent());
    }
};

Streaming streaming = new Streaming(client);
try {
    Shutdownable shutdownable = streaming.localPublic(handler);
    Thread.sleep(10000L);
    shutdownable.shutdown();
} catch (Exception e) {
    e.printStackTrace();
}
```

Raw error message is following, followers_count=97000000000  just and it may be cheating account such as spam:
```
Exception in thread "Thread-1" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 97000000000 at line 1 column 2260 path $.account.followers_count
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:242)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:232)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at com.google.gson.Gson.fromJson(Gson.java:905)
        at com.google.gson.Gson.fromJson(Gson.java:876)
        at com.sys1yagi.mastodon4j.api.method.Streaming$federatedPublic$1.run(Streaming.kt:42)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: Expected an int but was 97000000000 at line 1 column 2260 path $.account.followers_count
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1172)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:240)
        ... 13 more
```

**Comment by andregasser** [comment]
Hello @lamrongol Thanks for providing the insights. I thought something similar. But still, the lib should be able to parse it. I have just merged PR https://github.com/andregasser/bigbone/pull/178 from @Siddharth052002 that came in half an hour ago. Will publish a new snapshot build within the next few mins. If you want to give it a spin, let me know how it went. If there's stilll an issue with it, feel free to reopen this issue here. Cheers, André
